apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  container:
  - name: nginx
    image: nginx
    # envFrom will place all the key values from configMap
    envFrom:
    - configMapKeyRef:
        name: indix

    # env:
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: indix
    #       key: course
    # - name: trainer
    #   valueFrom:
    #     configMapKeyRef:
    #       name: indix
    #       key: trainer
    # - name: Repo
    #   valueFrom:
    #     configMapKeyRef:
    #       name: indix
    #       key: github
