kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 82 # service port like load balancer
    targetPort: 82 #nginx port

#kubectl apply -f 13-service.yaml
#kubectl get service
#kubectl describe service nginx
#kubectl get pods -o wide