apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 # service port like load balancer
    targetPort: 80 #nginx port
    nodeport: 32760

#kubectl apply -f <filename>
#kubectl get svc > it will show external and node port and Cluster IP
#kubectl get pods -o wide > to know pod running on which server
#kubernates recommand 30000-32767