apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    model: deploy
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: web
      project: test-project
#pod defination    
  template:
    metadata:
      labels:
        app: nginx
        tier: web
        project: test-project
        extra-key: extra-value
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl

#kubectl get deployments
#kubectl get replicaset
#watch kubectl get pods