apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "expense-ebs" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic
  labels:
    purpose: ebs-static
    project: expense
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic
---

#kubectl get sc (to view storage class)
#RECLAIM POLICY DELETE 59:31 min 01-JULY
#kubectl api-resources (To view resources)
#kubectl edit sc expense-ebs (retain policy cannot be edited)
#kubectl delete sc expense-ebs
#kubectl apply -f 02-ebs-dynamic.yaml